modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="tempus"
version="1.0.0"
displayName="Tempus"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="ARCADIA, MCreator"

[[dependencies.tempus]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




